const MAX_EMPLOYEES=30;
const STORE={config:'sak_config_v2',employees:'sak_employees_v2',punches:'sak_punches_v2',attempts:'sak_attempts_v2'};
const $=id=>document.getElementById(id);
let selectedEmployeeId=null,enteredPin='',adminUnlocked=false;
const load=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k))??fallback}catch{return fallback}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const config=()=>load(STORE.config,null),employees=()=>load(STORE.employees,[]),punches=()=>load(STORE.punches,[]);
function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
function b64(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function random(n=16){const a=new Uint8Array(n);crypto.getRandomValues(a);return a}
async function hashPin(pin,salt){return b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${salt}:${pin}`)))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initials(name=''){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function message(id,text,type='error'){const el=$(id);if(!el)return;el.innerHTML=text?`<div class="notice ${type==='ok'?'ok':type==='warn'?'warn':''}">${esc(text)}</div>`:''}
function nowIso(){return new Date().toISOString()}
function localDateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dayStart(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);return x}
function weekStart(){const d=dayStart(),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d}
function monthStart(){const d=dayStart();d.setDate(1);return d}
function fmtDuration(ms){const m=Math.max(0,Math.floor(ms/60000));return `${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`}
function formatDateTime(iso){const d=new Date(iso);return `${d.toLocaleDateString([],{weekday:'short',day:'2-digit',month:'short'})} ${d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`}
function employeePunches(id){return punches().filter(p=>p.employeeId===id).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp))}
function employeeState(id){return employeePunches(id)[0]?.type==='IN'?'IN':'OUT'}
function durationFor(records,includeOpen=false){let ms=0,start=null;[...records].sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)).forEach(p=>{if(p.type==='IN')start=new Date(p.timestamp);else if(p.type==='OUT'&&start){ms+=new Date(p.timestamp)-start;start=null}});if(includeOpen&&start)ms+=Date.now()-start;return Math.max(0,ms)}
function filteredPunches(period='week',employeeId='all') {let list=punches();if(employeeId!=='all')list=list.filter(p=>p.employeeId===employeeId);let start=null;if(period==='today')start=dayStart();if(period==='week')start=weekStart();if(period==='month')start=monthStart();if(start)list=list.filter(p=>new Date(p.timestamp)>=start);return list.sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp))}

function boot(){
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
  migrateLegacy();tick();setInterval(tick,1000);
  if(!config())$('setupView').classList.remove('hidden');else openKiosk();
}
function tick(){const d=new Date();$('clock').textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('date').textContent=d.toLocaleDateString([],{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('todayDate').textContent=d.toLocaleDateString([],{day:'numeric',month:'short'})}
async function migrateLegacy(){
  if(config()||!localStorage.getItem('sa_profile_v1'))return;
  try{const old=JSON.parse(localStorage.getItem('sa_profile_v1')),oldPunches=JSON.parse(localStorage.getItem('sa_punches_v1')||'[]');const adminSalt=b64(random()),adminHash=await hashPin('123456',adminSalt);save(STORE.config,{org:'Staff Attendance',manager:'Manager',adminSalt,adminHash,createdAt:nowIso(),migrated:true});const emp={id:uid(),name:old.name||'Employee',code:old.employeeId||'001',salt:old.salt,pinHash:old.pinHash,active:true,createdAt:nowIso()};save(STORE.employees,[emp]);save(STORE.punches,oldPunches.map(p=>({...p,employeeId:emp.id,method:p.verified||'PIN'})));}catch{}
}
async function createKiosk(){message('setupMsg','');const org=$('setupOrg').value.trim(),manager=$('setupManager').value.trim(),pin=$('setupPin').value,pin2=$('setupPin2').value;if(!org||!manager)return message('setupMsg','Enter the organisation and manager name.');if(!/^\d{6}$/.test(pin)||pin!==pin2)return message('setupMsg','Use matching six-digit manager PINs.');const adminSalt=b64(random()),adminHash=await hashPin(pin,adminSalt);save(STORE.config,{org,manager,adminSalt,adminHash,createdAt:nowIso()});save(STORE.employees,[]);save(STORE.punches,[]);$('setupView').classList.add('hidden');openKiosk()}
function openKiosk(){adminUnlocked=false;$('adminView').classList.add('hidden');$('kioskView').classList.remove('hidden');const c=config();$('brandName').textContent=c?.org||'Staff Attendance';renderEmployees();renderToday()}
function showKioskTab(tab){$('clockPage').classList.toggle('hidden',tab!=='clock');$('todayPage').classList.toggle('hidden',tab!=='today');$('clockTab').classList.toggle('active',tab==='clock');$('todayTab').classList.toggle('active',tab==='today');if(tab==='today')renderToday()}
function renderEmployees(){const all=employees().filter(e=>e.active!==false),q=$('employeeSearch').value.trim().toLowerCase(),list=all.filter(e=>`${e.name} ${e.code}`.toLowerCase().includes(q));$('employeeCount').textContent=`${all.length} employee${all.length===1?'':'s'}`;$('clockedInCount').textContent=`${all.filter(e=>employeeState(e.id)==='IN').length} clocked in`;$('noEmployees').classList.toggle('hidden',all.length>0);$('employeeGrid').innerHTML=list.map(e=>`<button class="employee-card" onclick="selectEmployee('${e.id}')"><div class="avatar">${esc(initials(e.name))}</div><div class="employee-name">${esc(e.name)}</div><div class="employee-code">${esc(e.code)}</div><div class="employee-status ${employeeState(e.id)==='OUT'?'out':''}">${employeeState(e.id)==='IN'?'● Clocked in':'○ Not clocked in'}</div></button>`).join('')}
function selectEmployee(id){const e=employees().find(x=>x.id===id);if(!e)return;selectedEmployeeId=id;enteredPin='';message('employeeMsg','');$('modalAvatar').textContent=initials(e.name);$('modalName').textContent=e.name;$('modalCode').textContent=`Employee ${e.code}`;const state=employeeState(id);$('modalStatus').textContent=state==='IN'?'Currently clocked in':'Not clocked in';$('confirmPunchBtn').textContent=state==='IN'?'Clock Out':'Clock In';$('confirmPunchBtn').className=`btn ${state==='IN'?'danger':'success'}`;$('employeeModal').classList.remove('hidden');updatePinDots()}
function closeEmployeeModal(){$('employeeModal').classList.add('hidden');enteredPin='';selectedEmployeeId=null}
function keypad(v){if(v==='clear')enteredPin='';else if(v==='back')enteredPin=enteredPin.slice(0,-1);else if(enteredPin.length<6)enteredPin+=v;message('employeeMsg','');updatePinDots()}
function updatePinDots(){$('pinDots').textContent=Array.from({length:6},(_,i)=>i<enteredPin.length?'●':'○').join(' ');$('confirmPunchBtn').disabled=enteredPin.length!==6}
function attemptKey(id){return `emp:${id}`}
function getAttempt(id){const a=load(STORE.attempts,{});return a[attemptKey(id)]||{count:0,lockedUntil:0}}
function recordFailure(id){const all=load(STORE.attempts,{}),k=attemptKey(id),current=all[k]||{count:0,lockedUntil:0};current.count++;if(current.count>=5){current.lockedUntil=Date.now()+60000;current.count=0}all[k]=current;save(STORE.attempts,all);return current}
function clearFailures(id){const all=load(STORE.attempts,{});delete all[attemptKey(id)];save(STORE.attempts,all)}
async function confirmEmployeePunch(){const e=employees().find(x=>x.id===selectedEmployeeId);if(!e)return;const a=getAttempt(e.id);if(a.lockedUntil>Date.now())return message('employeeMsg',`Too many incorrect attempts. Try again in ${Math.ceil((a.lockedUntil-Date.now())/1000)} seconds.`);if(await hashPin(enteredPin,e.salt)!==e.pinHash){recordFailure(e.id);enteredPin='';updatePinDots();return message('employeeMsg','Incorrect PIN. No attendance was recorded.')}clearFailures(e.id);const list=employeePunches(e.id),last=list[0];if(last&&Date.now()-new Date(last.timestamp)<30000)return message('employeeMsg','Please wait 30 seconds before another punch.','warn');const type=employeeState(e.id)==='IN'?'OUT':'IN',all=punches();all.push({id:uid(),employeeId:e.id,type,timestamp:nowIso(),method:'EMPLOYEE_PIN',deviceId:getDeviceId()});save(STORE.punches,all);message('employeeMsg',`${type==='IN'?'Clock-in':'Clock-out'} recorded successfully.`,'ok');renderEmployees();renderToday();setTimeout(closeEmployeeModal,1300)}
function getDeviceId(){let id=localStorage.getItem('sak_device_id');if(!id){id=uid();localStorage.setItem('sak_device_id',id)}return id}
function renderToday(){const list=filteredPunches('today');const es=employees();$('todayActivity').innerHTML=list.length?list.map(p=>{const e=es.find(x=>x.id===p.employeeId);return `<div class="row"><div><div class="row-title">${esc(e?.name||'Unknown employee')}</div><div class="row-sub">${esc(e?.code||'')} · ${p.type==='IN'?'Clock In':'Clock Out'}</div></div><div style="text-align:right"><b>${new Date(p.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</b><div class="row-sub">PIN verified</div></div></div>`}).join(''):'<div class="empty">No attendance recorded today.</div>'}

function openAdminLogin(){message('adminLoginMsg','');$('adminLoginPin').value='';$('adminLoginModal').classList.remove('hidden');setTimeout(()=>$('adminLoginPin').focus(),100)}
function closeAdminLogin(){$('adminLoginModal').classList.add('hidden')}
async function adminLogin(){const c=config(),pin=$('adminLoginPin').value;if(await hashPin(pin,c.adminSalt)!==c.adminHash)return message('adminLoginMsg','Incorrect manager PIN.');closeAdminLogin();adminUnlocked=true;$('kioskView').classList.add('hidden');$('adminView').classList.remove('hidden');$('adminOrg').textContent=c.org;$('adminManager').textContent=`Manager: ${c.manager}`;showAdminTab('dashboard');renderAdmin()}
function exitAdmin(){openKiosk()}
function showAdminTab(tab){['dashboard','staff','reports','backup'].forEach(x=>{$(`admin${x[0].toUpperCase()+x.slice(1)}`).classList.toggle('hidden',x!==tab);$(`admin${x[0].toUpperCase()+x.slice(1)}Tab`).classList.toggle('active',x===tab)});if(tab==='dashboard')renderAdmin();if(tab==='staff')renderStaff();if(tab==='reports')setupReports()}
function renderAdmin(){const es=employees().filter(e=>e.active!==false),today=filteredPunches('today'),week=filteredPunches('week');$('statEmployees').textContent=es.length;$('statClockedIn').textContent=es.filter(e=>employeeState(e.id)==='IN').length;$('statToday').textContent=today.length;$('statWeekHours').textContent=fmtDuration(durationFor(week,true));const inside=es.filter(e=>employeeState(e.id)==='IN');$('currentlyIn').innerHTML=inside.length?inside.map(e=>{const last=employeePunches(e.id)[0];return `<div class="row"><div><div class="row-title"><span class="status-dot in"></span>${esc(e.name)}</div><div class="row-sub">${esc(e.code)}</div></div><div><b>${new Date(last.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</b><div class="row-sub">Clocked in</div></div></div>`}).join(''):'<div class="empty">No employees are currently clocked in.</div>'}
async function addEmployee(){message('staffMsg','');const list=employees(),active=list.filter(e=>e.active!==false);if(active.length>=MAX_EMPLOYEES)return message('staffMsg','The 30-employee limit has been reached.');const name=$('newEmployeeName').value.trim(),code=$('newEmployeeCode').value.trim(),pin=$('newEmployeePin').value;if(!name||!code)return message('staffMsg','Enter the employee name and number.');if(!/^\d{6}$/.test(pin))return message('staffMsg','Enter a six-digit employee PIN.');if(list.some(e=>e.code.toLowerCase()===code.toLowerCase()))return message('staffMsg','That employee number is already in use.');const salt=b64(random()),pinHash=await hashPin(pin,salt);list.push({id:uid(),name,code,salt,pinHash,active:true,createdAt:nowIso()});save(STORE.employees,list);$('newEmployeeName').value='';$('newEmployeeCode').value='';$('newEmployeePin').value='';message('staffMsg',`${name} was added successfully.`,'ok');renderStaff();renderEmployees()}
function renderStaff(){const list=employees().filter(e=>e.active!==false);$('staffLimit').textContent=`${list.length} / ${MAX_EMPLOYEES}`;$('staffList').innerHTML=list.length?list.sort((a,b)=>a.name.localeCompare(b.name)).map(e=>`<div class="row"><div><div class="row-title">${esc(e.name)}</div><div class="row-sub">${esc(e.code)} · ${employeeState(e.id)==='IN'?'Clocked in':'Clocked out'}</div></div><div class="actions"><button class="btn secondary mini" onclick="resetEmployeePin('${e.id}')">PIN</button><button class="btn danger mini" onclick="removeEmployee('${e.id}')">Remove</button></div></div>`).join(''):'<div class="empty">No employees registered.</div>'}
async function resetEmployeePin(id){const e=employees().find(x=>x.id===id);if(!e)return;const pin=prompt(`Enter a new six-digit PIN for ${e.name}`);if(pin===null)return;if(!/^\d{6}$/.test(pin))return alert('The PIN must contain exactly six digits.');const list=employees(),target=list.find(x=>x.id===id);target.salt=b64(random());target.pinHash=await hashPin(pin,target.salt);save(STORE.employees,list);alert(`${e.name}'s PIN was changed.`)}
function removeEmployee(id){const list=employees(),e=list.find(x=>x.id===id);if(!e||!confirm(`Remove ${e.name} from the active employee list? Existing attendance records will be retained.`))return;e.active=false;e.removedAt=nowIso();save(STORE.employees,list);renderStaff();renderEmployees()}
function setupReports(){const sel=$('reportEmployee'),current=sel.value;sel.innerHTML='<option value="all">All employees</option>'+employees().filter(e=>e.active!==false).sort((a,b)=>a.name.localeCompare(b.name)).map(e=>`<option value="${e.id}">${esc(e.name)} (${esc(e.code)})</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current;renderReports()}
function renderReports(){const empId=$('reportEmployee').value||'all',period=$('reportPeriod').value||'week',list=filteredPunches(period,empId),es=employees();$('reportHours').textContent=fmtDuration(durationFor(list,period!=='all'));$('reportPunches').textContent=list.length;$('reportRows').innerHTML=list.length?list.map(p=>{const e=es.find(x=>x.id===p.employeeId);return `<div class="row"><div><div class="row-title">${esc(e?.name||'Unknown')}</div><div class="row-sub">${p.type==='IN'?'Clock In':'Clock Out'} · ${formatDateTime(p.timestamp)}</div></div><button class="btn danger mini" onclick="deletePunch('${p.id}')">Delete</button></div>`}).join(''):'<div class="empty">No records for this selection.</div>'}
function deletePunch(id){if(!confirm('Delete this attendance record? This action cannot be undone.'))return;save(STORE.punches,punches().filter(p=>p.id!==id));renderReports();renderAdmin();renderEmployees();renderToday()}
function addMissedPunch(){const active=employees().filter(e=>e.active!==false);if(!active.length)return alert('Add an employee first.');const code=prompt('Enter the employee number');if(code===null)return;const e=active.find(x=>x.code.toLowerCase()===code.trim().toLowerCase());if(!e)return alert('Employee number not found.');const type=(prompt('Enter IN or OUT','IN')||'').trim().toUpperCase();if(!['IN','OUT'].includes(type))return alert('Punch type must be IN or OUT.');const value=prompt('Enter date and time as YYYY-MM-DD HH:MM',new Date().toISOString().slice(0,16).replace('T',' '));if(!value)return;const d=new Date(value.replace(' ','T'));if(Number.isNaN(d.getTime()))return alert('Invalid date or time.');const list=punches();list.push({id:uid(),employeeId:e.id,type,timestamp:d.toISOString(),method:'MANAGER_CORRECTION',deviceId:getDeviceId(),editedAt:nowIso()});save(STORE.punches,list);renderReports();renderAdmin();renderEmployees();alert('Missed punch added.')}
function exportCsv(){const empId=$('reportEmployee').value||'all',period=$('reportPeriod').value||'week',list=filteredPunches(period,empId),es=employees(),rows=[['Employee Number','Employee Name','Punch Type','Date','Time','Verification']];list.slice().reverse().forEach(p=>{const e=es.find(x=>x.id===p.employeeId),d=new Date(p.timestamp);rows.push([e?.code||'',e?.name||'',p.type,d.toLocaleDateString('en-CA'),d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}),p.method||'PIN'])});download(`attendance-${period}-${localDateKey()}.csv`,rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}
function exportBackup(){download(`attendance-backup-${localDateKey()}.json`,JSON.stringify({version:2,exportedAt:nowIso(),config:config(),employees:employees(),punches:punches(),deviceId:getDeviceId()},null,2),'application/json');message('backupMsg','Backup downloaded successfully.','ok')}
function download(name,content,type){const blob=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function restoreBackup(ev){const file=ev.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data.config||!Array.isArray(data.employees)||!Array.isArray(data.punches))throw new Error();if(!confirm('Restore this backup? Current data on the device will be replaced.'))return;save(STORE.config,data.config);save(STORE.employees,data.employees);save(STORE.punches,data.punches);message('backupMsg','Backup restored successfully.','ok');renderAdmin();renderStaff();setupReports()}catch{message('backupMsg','This is not a valid attendance backup.')}};reader.readAsText(file);ev.target.value=''}
async function changeAdminPin(){const c=config(),oldPin=prompt('Enter the current manager PIN');if(oldPin===null)return;if(await hashPin(oldPin,c.adminSalt)!==c.adminHash)return alert('Current manager PIN is incorrect.');const pin=prompt('Enter the new six-digit manager PIN');if(pin===null)return;if(!/^\d{6}$/.test(pin))return alert('The PIN must contain exactly six digits.');const pin2=prompt('Confirm the new manager PIN');if(pin!==pin2)return alert('The PINs do not match.');c.adminSalt=b64(random());c.adminHash=await hashPin(pin,c.adminSalt);save(STORE.config,c);alert('Manager PIN changed successfully.')}

document.addEventListener('visibilitychange',()=>{if(document.hidden){closeEmployeeModal();closeAdminLogin();if(adminUnlocked)exitAdmin()}});
boot();
