const DB='https://mantledb.sh/v2';
const LS={connection:'nsa_cloud_connection_v1',role:'nsa_cloud_role_v1',pending:'nsa_pending_v1'};
const MAX_EMPLOYEES=30;
const PRESET=[
['Kuarina Nepembe','EMP001','190002'],['Silvanus Leide','EMP002','831946'],['Petrus Hambeleleni','EMP003','646405'],['Krestina Amutenya','EMP004','308114'],['Teopolina Petrus','EMP005','198664'],['Kristofina Kavetimwah','EMP006','726394'],['Shipila Penarius','EMP007','950878'],['Martha Alugodhi','EMP008','177463'],['Elizabeth Hango','EMP009','588412'],['Ester Nikodemus','EMP010','489048'],['Immanuel Evelina','EMP011','126719'],['Rosalia Nangolo','EMP012','120859'],['Emilia Jonathan','EMP013','648381'],['Frieda Gebhard','EMP014','741474'],['Maria K.','EMP015','357999'],['Shilumbu Lavinia','EMP016','824268'],['Simon Elizabeth','EMP017','384718'],['Nikanor Maria','EMP018','805314'],['Johannes Selma','EMP019','796285'],['Martha Tobias','EMP020','437091'],['Hilma Sevelus','EMP021','803380'],['Evelina Magongo','EMP022','677673'],['Elizabeth N. Shatiwa','EMP023','845949'],['Sylvester Siyambango','EMP024','710260'],['Penda Malima Enflies','EMP025','584715']];
let connection=null, role=null, cloudConfig=null, cloudEmployees=[], cloudStatus={}, managerRecords=[], selectedEmployee=null, pendingPair=null, managerUnlocked=false;
const $=id=>document.getElementById(id);
const uuid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const b64=u8=>btoa(String.fromCharCode(...u8)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const b64text=s=>b64(new TextEncoder().encode(s));
const unb64text=s=>{s=s.replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';return new TextDecoder().decode(Uint8Array.from(atob(s),c=>c.charCodeAt(0)))};
const random=(n=16)=>{const a=new Uint8Array(n);crypto.getRandomValues(a);return a};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=n=>String(n||'?').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const monthKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
const now=()=>new Date().toISOString();
const loadLocal=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const saveLocal=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function message(id,text,type='error'){const e=$(id);if(e)e.innerHTML=text?`<div class="notice ${type==='ok'?'ok':type==='warn'?'warn':''}">${esc(text)}</div>`:''}
async function hashPin(pin,salt){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${salt}:${pin}`))))}
function api(path,opts={}){if(!connection)throw new Error('This device is not connected.');const headers={'Content-Type':'application/json','X-Mantle-Key':connection.key,...(opts.headers||{})};return fetch(`${DB}/${connection.ns}/${path}`,{...opts,headers})}
async function readEntry(path,fallback){const r=await api(path);if(r.status===404)return fallback;if(!r.ok)throw new Error(`Online service error (${r.status})`);return r.json()}
async function writeEntry(path,data){const r=await api(path,{method:'POST',body:JSON.stringify(data)});if(!r.ok)throw new Error(`Could not save online (${r.status})`);return r.json()}
function setConnectionStatus(text,ok=true){$('connectionStatus').textContent=text;$('connectionStatus').className=ok?'online':'offline'}
function hideAll(){['firstSetup','pairScreen','pairConfirm','managerLogin','kioskApp','managerApp'].forEach(id=>$(id).classList.add('hidden'))}
function tick(){const d=new Date();if($('clock'))$('clock').textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if($('date'))$('date').textContent=d.toLocaleDateString([],{weekday:'long',day:'numeric',month:'long',year:'numeric'});if($('todayBadge'))$('todayBadge').textContent=d.toLocaleDateString([],{day:'numeric',month:'short'})}
async function boot(){tick();setInterval(tick,1000);window.addEventListener('online',()=>{setConnectionStatus('Online',true);syncPending()});window.addEventListener('offline',()=>setConnectionStatus('Offline — punches will queue',false));
parsePairFragment();connection=loadLocal(LS.connection,null);role=localStorage.getItem(LS.role);if(pendingPair){hideAll();$('pairOrg').textContent=pendingPair.org||'Northern Staff Attendance';$('pairConfirm').classList.remove('hidden');return}if(!connection){hideAll();$('firstSetup').classList.remove('hidden');setConnectionStatus('Not yet connected',false);return}try{cloudConfig=await readEntry('config',null);if(!cloudConfig)throw new Error('Configuration missing');$('brandTitle').textContent=cloudConfig.org;setConnectionStatus(navigator.onLine?'Online cloud system':'Offline',navigator.onLine);if(role==='kiosk')openKiosk();else openManagerLogin()}catch(e){setConnectionStatus('Could not reach online records',false);hideAll();if(role==='kiosk')openKiosk(true);else $('managerLogin').classList.remove('hidden')}}
function parsePairFragment(){const h=location.hash;if(!h.startsWith('#pair='))return;try{pendingPair=JSON.parse(unb64text(h.slice(6)));history.replaceState(null,'',location.pathname+location.search)}catch{pendingPair=null}}
async function createCloudSystem(){message('setupMsg','');const org=$('setupOrg').value.trim(),manager=$('setupManager').value.trim(),pin=$('setupPin').value,pin2=$('setupPin2').value;if(!org||!manager)return message('setupMsg','Enter the organisation and manager name.');if(!/^\d{6}$/.test(pin)||pin!==pin2)return message('setupMsg','Use matching six-digit manager PINs.');const btn=event.currentTarget;btn.disabled=true;btn.innerHTML='<span class="spinner"></span>Creating online system';try{const ns=`northstaff-${Date.now().toString(36)}-${b64(random(7)).toLowerCase()}`;const claim=await fetch(`${DB}/claim/${ns}`);if(!claim.ok)throw new Error('The online datastore could not be created.');const result=await claim.json();connection={ns,key:result.key};saveLocal(LS.connection,connection);localStorage.setItem(LS.role,'manager');role='manager';const salt=b64(random()),managerHash=await hashPin(pin,salt);cloudConfig={org,manager,managerSalt:salt,managerHash,createdAt:now(),version:1};cloudEmployees=[];for(const [name,code,epin] of PRESET){const esalt=b64(random());cloudEmployees.push({id:uuid(),name,code,salt:esalt,pinHash:await hashPin(epin,esalt),active:true,createdAt:now()})}cloudStatus={};await writeEntry('config',cloudConfig);await writeEntry('employees',cloudEmployees);await writeEntry('status',cloudStatus);await writeEntry(`punches-${monthKey()}`,[]);$('brandTitle').textContent=org;setConnectionStatus('Online cloud system',true);showPairScreen()}catch(e){console.error(e);message('setupMsg','The online system could not be created. Check the internet connection and try again.')}finally{btn.disabled=false;btn.textContent='Create Online System'}}
function pairPayload(roleName){return {ns:connection.ns,key:connection.key,role:roleName,org:cloudConfig?.org||'Northern Staff Attendance'}}
function pairLink(roleName='kiosk'){return `${location.origin}${location.pathname}#pair=${b64text(JSON.stringify(pairPayload(roleName)))}`}
function showPairScreen(){hideAll();const link=pairLink('kiosk');$('kioskPairLink').textContent=link;$('pairScreen').classList.remove('hidden')}
async function copyPairLink(){await navigator.clipboard.writeText(pairLink('kiosk'));alert('Staff-phone link copied. Send it to the shared phone in the north.')}
async function sharePairLink(){const data={title:'Northern Staff Clocking',text:'Open this private link on the shared staff phone:',url:pairLink('kiosk')};if(navigator.share)await navigator.share(data);else copyPairLink()}
function confirmPairing(){connection={ns:pendingPair.ns,key:pendingPair.key};role=pendingPair.role||'kiosk';saveLocal(LS.connection,connection);localStorage.setItem(LS.role,role);pendingPair=null;location.reload()}
function cancelPairing(){pendingPair=null;location.hash='';location.reload()}
function openManagerLogin(){hideAll();$('managerLoginOrg').textContent=cloudConfig?.org||'Northern Staff Attendance';$('managerPin').value='';$('managerLogin').classList.remove('hidden')}
