async function managerLogin(){message('managerLoginMsg','');try{cloudConfig=cloudConfig||await readEntry('config',null);const h=await hashPin($('managerPin').value,cloudConfig.managerSalt);if(h!==cloudConfig.managerHash)return message('managerLoginMsg','Incorrect manager PIN.');managerUnlocked=true;await openManager()}catch(e){message('managerLoginMsg','Could not connect to the online records. Check the internet connection.')}}
async function openManager(){hideAll();$('managerApp').classList.remove('hidden');$('managerOrgTitle').textContent=cloudConfig.org;$('managerNameText').textContent=`Manager: ${cloudConfig.manager}`;$('recordMonth').value=monthKey();await refreshManagerData();showManagerTab('overview')}
function managerLogout(){managerUnlocked=false;openManagerLogin()}
async function refreshManagerData(){try{[cloudEmployees,cloudStatus]=await Promise.all([readEntry('employees',[]),readEntry('status',{})]);setConnectionStatus('Online — live records',true);renderManagerOverview();renderEmployeeAdmin();setupRecordEmployee();updatePairDisplay()}catch(e){setConnectionStatus('Unable to refresh online data',false)}}
function showManagerTab(tab){const map={overview:'managerOverview',employees:'managerEmployees',records:'managerRecords',pair:'managerPair'};Object.entries(map).forEach(([k,id])=>{$(id).classList.toggle('hidden',k!==tab);$(`m${k[0].toUpperCase()+k.slice(1)}Tab`).classList.toggle('active',k===tab)});if(tab==='overview')refreshManagerData();if(tab==='employees')renderEmployeeAdmin();if(tab==='records')loadManagerRecords();if(tab==='pair')updatePairDisplay()}
function renderManagerOverview(){const active=cloudEmployees.filter(e=>e.active!==false),values=Object.values(cloudStatus);$('statEmployees').textContent=active.length;$('statIn').textContent=values.filter(s=>s.state==='IN').length;$('statBreak').textContent=values.filter(s=>s.state==='BREAK').length;$('statPending').textContent='—';const rows=active.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(e=>{const s=cloudStatus[e.id]||{state:'OUT'};return `<div class="row"><div><div class="row-title">${esc(e.name)}</div><div class="row-sub">${esc(e.code)}</div></div><div style="text-align:right"><b>${s.state==='IN'?'Working':s.state==='BREAK'?'On break':'Off duty'}</b><div class="row-sub">${s.timestamp?new Date(s.timestamp).toLocaleString():''}</div></div></div>`}).join('');$('statusRows').innerHTML=rows||'<div class="empty">No employees registered.</div>'}
function renderEmployeeAdmin(){const active=cloudEmployees.filter(e=>e.active!==false);$('managerEmployeeCount').textContent=`${active.length} / ${MAX_EMPLOYEES}`;$('employeeAdminRows').innerHTML=cloudEmployees.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(e=>`<div class="row"><div><div class="row-title">${esc(e.name)}</div><div class="row-sub">${esc(e.code)} · ${e.active===false?'Inactive':'Active'}</div></div><div class="actions"><button class="btn mini ghost" onclick="resetEmployeePin('${e.id}')">Reset PIN</button><button class="btn mini ${e.active===false?'success':'danger'}" onclick="toggleEmployee('${e.id}')">${e.active===false?'Activate':'Deactivate'}</button></div></div>`).join('')}
async function addEmployee(){message('employeeAdminMsg','');const active=cloudEmployees.filter(e=>e.active!==false);if(active.length>=MAX_EMPLOYEES)return message('employeeAdminMsg','The 30-employee limit has been reached.');const name=$('newEmpName').value.trim(),code=$('newEmpCode').value.trim(),pin=$('newEmpPin').value;if(!name||!code)return message('employeeAdminMsg','Enter the employee name and employee number.');if(!/^\d{6}$/.test(pin))return message('employeeAdminMsg','The employee PIN must contain six digits.');if(cloudEmployees.some(e=>e.code.toLowerCase()===code.toLowerCase()))return message('employeeAdminMsg','That employee number is already in use.');const salt=b64(random());cloudEmployees.push({id:uuid(),name,code,salt,pinHash:await hashPin(pin,salt),active:true,createdAt:now()});try{await writeEntry('employees',cloudEmployees);$('newEmpName').value='';$('newEmpCode').value='';$('newEmpPin').value='';message('employeeAdminMsg',`${name} was added successfully.`,'ok');renderEmployeeAdmin();setupRecordEmployee()}catch(e){message('employeeAdminMsg','Could not save the employee online.')}}
async function resetEmployeePin(id){const e=cloudEmployees.find(x=>x.id===id),pin=prompt(`Enter a new six-digit PIN for ${e.name}`);if(pin===null)return;if(!/^\d{6}$/.test(pin))return alert('PIN must contain six digits.');e.salt=b64(random());e.pinHash=await hashPin(pin,e.salt);await writeEntry('employees',cloudEmployees);alert('Employee PIN updated.')}
async function toggleEmployee(id){const e=cloudEmployees.find(x=>x.id===id);e.active=e.active===false;await writeEntry('employees',cloudEmployees);renderEmployeeAdmin();renderManagerOverview()}
function setupRecordEmployee(){const s=$('recordEmployee'),v=s.value;s.innerHTML='<option value="all">All employees</option>'+cloudEmployees.map(e=>`<option value="${e.id}">${esc(e.name)} (${esc(e.code)})</option>`).join('');if([...s.options].some(o=>o.value===v))s.value=v}
async function loadManagerRecords(){try{managerRecords=await readEntry(`punches-${$('recordMonth').value||monthKey()}`,[]);renderManagerRecords()}catch(e){$('recordRows').innerHTML='<div class="notice">Could not load records.</div>'}}
function filteredManagerRecords(){const id=$('recordEmployee').value||'all';return managerRecords.filter(p=>id==='all'||p.employeeId===id).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp))}
function paidDuration(list){const by={};list.slice().sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)).forEach(p=>(by[p.employeeId]??=[]).push(p));let ms=0;Object.values(by).forEach(arr=>{let work=null,breakStart=null;arr.forEach(p=>{if(p.type==='IN'){work=new Date(p.timestamp);breakStart=null}else if(p.type==='BREAK_START'&&work&&!breakStart)breakStart=new Date(p.timestamp);else if(p.type==='BREAK_END'&&breakStart){work=new Date(new Date(work).getTime()+(new Date(p.timestamp)-breakStart));breakStart=null}else if(p.type==='OUT'&&work){const end=new Date(p.timestamp);ms+=Math.max(0,end-work-(breakStart?end-breakStart:0));work=null;breakStart=null}})});return ms}
function fmt(ms){const m=Math.floor(Math.max(0,ms)/60000);return `${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`}
function typeLabel(t){return ({IN:'Clock In',BREAK_START:'Break Start',BREAK_END:'Break End',OUT:'Clock Out'})[t]||t}
function renderManagerRecords(){const list=filteredManagerRecords();$('recordCount').textContent=list.length;$('recordHours').textContent=fmt(paidDuration(list));$('recordRows').innerHTML=list.length?list.map(p=>{const e=cloudEmployees.find(x=>x.id===p.employeeId);return `<div class="row"><div><div class="row-title">${esc(e?.name||'Unknown')}</div><div class="row-sub">${typeLabel(p.type)} · ${new Date(p.timestamp).toLocaleString()}${p.note?' · '+esc(p.note):''}</div></div><button class="btn danger mini" onclick="deleteRecord('${p.id}')">Delete</button></div>`}).join(''):'<div class="empty">No records for this selection.</div>'}
async function deleteRecord(id){if(!confirm('Delete this punch?'))return;managerRecords=managerRecords.filter(p=>p.id!==id);await writeEntry(`punches-${$('recordMonth').value}`,managerRecords);renderManagerRecords()}
async function addCorrection(){const code=prompt('Employee number');if(!code)return;const e=cloudEmployees.find(x=>x.code.toLowerCase()===code.trim().toLowerCase());if(!e)return alert('Employee not found.');const type=(prompt('Type: IN, BREAK_START, BREAK_END or OUT','IN')||'').trim().toUpperCase();if(!['IN','BREAK_START','BREAK_END','OUT'].includes(type))return alert('Invalid punch type.');const value=prompt('Date/time: YYYY-MM-DD HH:MM',new Date().toISOString().slice(0,16).replace('T',' '));if(!value)return;const d=new Date(value.replace(' ','T'));if(Number.isNaN(d.getTime()))return alert('Invalid date/time.');const note=prompt('Reason for correction');if(!note)return alert('A reason is required.');const key=monthKey(d),list=await readEntry(`punches-${key}`,[]);list.push({id:uuid(),employeeId:e.id,type,timestamp:d.toISOString(),method:'MANAGER_CORRECTION',note,createdAt:now()});await writeEntry(`punches-${key}`,list);if(key===$('recordMonth').value){managerRecords=list;renderManagerRecords()}alert('Correction saved.')}
