function exportCsv(){const rows=[['Employee Number','Employee Name','Punch','Date','Time','Method','Note']];filteredManagerRecords().slice().reverse().forEach(p=>{const e=cloudEmployees.find(x=>x.id===p.employeeId),d=new Date(p.timestamp);rows.push([e?.code||'',e?.name||'',typeLabel(p.type),d.toLocaleDateString('en-CA'),d.toLocaleTimeString(),p.method||'',p.note||''])});const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`attendance-${$('recordMonth').value}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function updatePairDisplay(){if(!connection)return;const l=pairLink('kiosk');$('managerPairLink').textContent=l}
async function copyManagerPairLink(){await navigator.clipboard.writeText(pairLink('kiosk'));alert('Staff-phone link copied.')}
async function shareManagerPairLink(){const l=pairLink('kiosk');if(navigator.share)await navigator.share({title:'Northern Staff Clocking',url:l});else copyManagerPairLink()}
async function openKiosk(offline=false){hideAll();$('kioskApp').classList.remove('hidden');try{if(!offline){[cloudConfig,cloudEmployees,cloudStatus]=await Promise.all([readEntry('config',null),readEntry('employees',[]),readEntry('status',{})]);$('brandTitle').textContent=cloudConfig.org;setConnectionStatus('Online — connected to Windhoek',true)}}catch(e){cloudEmployees=loadLocal('nsa_employee_cache',[]);cloudStatus=loadLocal('nsa_status_cache',{});setConnectionStatus('Offline — punches will sync later',false)}saveLocal('nsa_employee_cache',cloudEmployees);saveLocal('nsa_status_cache',cloudStatus);renderKioskEmployees();renderToday();syncPending();setInterval(()=>{if(navigator.onLine)refreshKiosk()},30000)}
async function refreshKiosk(){try{[cloudEmployees,cloudStatus]=await Promise.all([readEntry('employees',cloudEmployees),readEntry('status',cloudStatus)]);saveLocal('nsa_employee_cache',cloudEmployees);saveLocal('nsa_status_cache',cloudStatus);renderKioskEmployees();renderToday();setConnectionStatus('Online — connected to Windhoek',true)}catch{setConnectionStatus('Offline — punches will sync later',false)}}
function renderKioskEmployees(){const q=$('searchEmployee').value.trim().toLowerCase(),active=cloudEmployees.filter(e=>e.active!==false),list=active.filter(e=>`${e.name} ${e.code}`.toLowerCase().includes(q));$('employeeCount').textContent=`${active.length} employees`;$('clockedInCount').textContent=`${Object.values(cloudStatus).filter(s=>s.state==='IN'||s.state==='BREAK').length} on site`;$('employeeGrid').innerHTML=list.map(e=>{const s=cloudStatus[e.id]?.state||'OUT';return `<button class="employee" onclick="selectEmployee('${e.id}')"><div class="avatar">${esc(initials(e.name))}</div><div class="emp-name">${esc(e.name)}</div><div class="emp-code">${esc(e.code)}</div><div class="emp-state ${s==='OUT'?'out':''}">${s==='IN'?'● Working':s==='BREAK'?'● On break':'○ Off duty'}</div></button>`}).join('');$('noEmployees').classList.toggle('hidden',active.length>0)}
function selectEmployee(id){selectedEmployee=cloudEmployees.find(e=>e.id===id);$('punchAvatar').textContent=initials(selectedEmployee.name);$('punchName').textContent=selectedEmployee.name;$('punchCode').textContent=selectedEmployee.code;$('punchPin').value='';message('punchMsg','');renderPunchActions();$('punchModal').classList.remove('hidden');setTimeout(()=>$('punchPin').focus(),100)}
function renderPunchActions(){const state=cloudStatus[selectedEmployee.id]?.state||'OUT',actions=state==='OUT'?[['IN','Clock In','success']]:state==='BREAK'?[['BREAK_END','End Break','success']]:[['BREAK_START','Start Break','warning'],['OUT','Clock Out','danger']];$('punchActions').innerHTML=actions.map(([t,l,c])=>`<button class="btn ${c}" onclick="performPunch('${t}')">${l}</button>`).join('')}
function closePunchModal(){$('punchModal').classList.add('hidden');selectedEmployee=null}
async function getGps(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),()=>resolve(null),{enableHighAccuracy:true,timeout:7000,maximumAge:30000})})}
function nextState(type){return type==='IN'||type==='BREAK_END'?'IN':type==='BREAK_START'?'BREAK':'OUT'}
async function performPunch(type){message('punchMsg','');const pin=$('punchPin').value;if(!/^\d{6}$/.test(pin))return message('punchMsg','Enter your six-digit PIN.');if(await hashPin(pin,selectedEmployee.salt)!==selectedEmployee.pinHash)return message('punchMsg','Incorrect PIN. No attendance was recorded.');const record={id:uuid(),employeeId:selectedEmployee.id,type,timestamp:now(),method:'EMPLOYEE_PIN',gps:await getGps(),device:navigator.userAgent.slice(0,160)};cloudStatus[selectedEmployee.id]={state:nextState(type),timestamp:record.timestamp,lastPunchId:record.id};saveLocal('nsa_status_cache',cloudStatus);renderKioskEmployees();try{await appendPunch(record);await writeEntry('status',cloudStatus);message('punchMsg',`${typeLabel(type)} recorded online successfully.`,'ok');setTimeout(closePunchModal,1200);renderToday()}catch(e){const q=loadLocal(LS.pending,[]);q.push(record);saveLocal(LS.pending,q);message('punchMsg',`${typeLabel(type)} saved on this phone. It will upload when the internet returns.`,'warn');updateQueueNotice();setTimeout(closePunchModal,1700)}}
async function appendPunch(record){const key=`punches-${monthKey(new Date(record.timestamp))}`,list=await readEntry(key,[]);if(!list.some(p=>p.id===record.id))list.push(record);await writeEntry(key,list)}
async function syncPending(){if(!connection||!navigator.onLine)return;let q=loadLocal(LS.pending,[]);if(!q.length){updateQueueNotice();return}const remain=[];for(const r of q){try{await appendPunch(r)}catch{remain.push(r)}}saveLocal(LS.pending,remain);try{await writeEntry('status',cloudStatus)}catch{}updateQueueNotice();if(!remain.length)refreshKiosk()}
function updateQueueNotice(){const q=loadLocal(LS.pending,[]);$('queueNotice').classList.toggle('hidden',!q.length);$('queueNotice').textContent=q.length?`${q.length} punch${q.length===1?'':'es'} waiting to upload. Keep the phone connected to the internet.`:''}
async function renderToday(){const key=`punches-${monthKey()}`;let list=[];try{list=await readEntry(key,[])}catch{}const today=new Date().toDateString();list=list.filter(p=>new Date(p.timestamp).toDateString()===today).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp));$('todayRows').innerHTML=list.length?list.map(p=>{const e=cloudEmployees.find(x=>x.id===p.employeeId);return `<div class="row"><div><div class="row-title">${esc(e?.name||'Unknown')}</div><div class="row-sub">${typeLabel(p.type)}</div></div><b>${new Date(p.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</b></div>`}).join(''):'<div class="empty">No punches recorded today.</div>'}
function showKioskTab(tab){$('kioskClock').classList.toggle('hidden',tab!=='clock');$('kioskToday').classList.toggle('hidden',tab!=='today');$('kioskClockTab').classList.toggle('active',tab==='clock');$('kioskTodayTab').classList.toggle('active',tab==='today');if(tab==='today')renderToday()}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&role==='kiosk')refreshKiosk()});boot();
